### ISSUE TITLE
"Security Key Enforcement" seems to be duplicated in the Brochure PDF.

### ISSUE THREAD

**Issue by onsamuse** [gregsramblings/google-cloud-4-words#20]
the title says it all :) I haven't checked the other formats.
thanks for this great tool.
cheers,
Raphaël

**Comment by 0xmc** [comment]
There are a number of repeated lines in the Identity and Security section of the v2019.7.17 version of the brochure, not just Security Key Enforcement.

**Comment by gregsramblings** [comment]
New brochure coming soon - and we fixed the dupes.Thanks!

**Comment by onsamuse** [comment]
Thanks Greg!
